### PR TITLE
dbmate-tupac: a dbmate wrapper for better schemas

### PR DESCRIPTION
**Pull request by jkeifer**
I have a problem with dbmate's schema handling. It will dump the entire database "schema only" into a file, and expects that file to be useful for reference. But much of the file can end up being changes due to things outside the current project's concerns.

For example, enabling an extension that creates functions/tables in the database will cause those to show up in the schema file. And things like partitions that change over time: even if nothing changes in the migrations, the dumped schema can show changes.

The "schema only" dump also excludes data that is effectively part of the schema itself. For example, the `thread_state` table defines a set of states that can be used for the `thread.status` field, and those rows are a fixed set of values enforcing the set of possible `thread.status` values. In effect, these "data" rows are as important as the info in a "schema only" dump to ensuring the database has the information it needs to work as expected.

As a result, it seems that the schema handling of dbmate does not give us what we want, so I created this wrapper implementing a new `verify` command that I think makes more sense. It does the following:

  - creates the database from the reference schema
  - dumps the database
  - drops the database
  - creates the database and applies all migrations
  - dumps the database
  - drops the database
  - diffs the dumps

If the diff shows no changes then the migrations and the reference schema are aligned.

Functionally, this means that dbmate commands no longer dump the schema into `schema.sql`, and we end up maintaining that file ourselves as the true schema the migraitons must match.

This means that some changes will need to be made both in a migration and in the reference schema. This is additional work. But it gives us a way to actually enforce that the schema is an effective reference for what we want to have in the database. In other words, this gives us a reference schema that is not subject to the limitations of the "schema only" dump supported by dbmate.

### CODE REVIEW

**Review by paulpilone — APPROVED** [review]

**Comment by jkeifer** [comment]
For reference, here is the `dbmate` discussion I've started to (hopefully) get feedback on a better long-term solution than this `dbmate-tupac` wrapper script: https://github.com/amacneil/dbmate/discussions/433.

**Comment by demiurg** [comment]
Why don't you guys use SQL Alchemy and Alembic? It kind of integrates with Pydantic too. I haven't used them in a while (team Django) implementing DB migrations seems like a daunting task, and it has been done many times before.

**Comment by jkeifer** [comment]
Hey Pavel! How'd you end up looking at this? 😄

Anyway, great question. We have a growing collection of ADRs that we plan to port into this repo at some point, one of which has some details about the initial investigation we did into ORMs/migration tools/etc, but short version is this:

1. the team is comfortable with raw sql, so managing migrations with a tool like `dbmate` does not seem daunting to us
1. we're targeting compatibility with multiple languages, so we want a schema that isn't tied to a specific ORM
1. we will be making certain types of queries an ORM would likely struggle to accommodate efficiently (time series aggregation), meaning if we did use an ORM it would end up being a rather leaky abstraction we'd have to work around with our own hand-rolled queries
1. as we are building a work queue in postgres, we will be making use of advisory locking...not sure if any ORMs would offer support for that
1. we want to make use of triggers and functions, which I don't believe would be possible with any ORMs beyond, again, a leaky abstraction

So an ORM is great if it fits your use case, but here we came to the conclusion it would add more overhead and limit what we could easily do. `dbmate` is a rather reasonable tool for managing migrations in a language/ORM agnostic manner, so we chose to use it to manage raw sql migrations. The only thing with it a mild disagreement with its behavior around the schema-only dumps it makes to see changes the migrations are making, hence this PR and the work contained within.

**Comment by demiurg** [comment]
I clicked E84 blog in LinkedIn -> E84 GitHub -> Swoop was on top :)

Using the most popular ORM for migrations does not preclude language agnosticism, or using raw SQL. You just potentially get more on top. If you think you will have less work overall with dbmate, that's great, but doesn't look like it.

Anyway, best of luck with the project :)

**Pull request merged**
